# .air.toml
[build]
# Command to build application
cmd = "go build -o ./tmp/main cmd/main.go"

# Directory to store the compiled binary
bin = "./tmp/main"

# Include these extensions for watching
include_ext = ["go", "tpl", "tmpl", "html"]

# Exclude these directories from watching
exclude_dir = ["vendor", "logs", "bin", "tmp", "migrations"]

# Exclude files by name or pattern
exclude_file = []

# Send logs to stdout
log = "air.log"

[runner]
# Command to run your binary
cmd = "./tmp/main"
