run:
  concurrency: 4

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - errcheck
    - govet
    - gofmt
    - staticcheck
    - unused
