version: '3.8'

services:
  db:
    image: postgres:15
    container_name: health_tracking_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: health_tracking_redis
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
